from decimal import Decimal
from locale import currency
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
        
PERCENTAGE_VALIDATOR = [MinValueValidator(0), MaxValueValidator(100)]

# Create your models here.
class Company(models.Model):
    ticker = models.CharField(max_length=10,primary_key=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    beta = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    volume_average = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    last_dividend = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    low =  models.DecimalField(max_digits=10, decimal_places=2, default=0)
    high = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    change = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    name = models.CharField(max_length=100)
    currency = models.CharField(max_length=10, default="USD")
    isin = models.CharField(max_length=100,default="")
    cusip = models.CharField(max_length=100,default="")
    exchange = models.CharField(max_length=100,default="")
    exchange_sort = models.CharField(max_length=100,default="")
    sector = models.CharField(max_length=100)
    industry = models.CharField(max_length=100)
    website = models.CharField(max_length=100,default="")
    description = models.TextField(null=True, blank=True)
    ceo = models.CharField(max_length=100,default="")
    country = models.CharField(max_length=100)
    city = models.CharField(max_length=100, null=True)
    number_of_employees = models.IntegerField(default=0)
    phone = models.CharField(max_length=100,default="")
    address = models.CharField(max_length=100,default="")
    state = models.CharField(max_length=100,default="")
    zip_code = models.CharField(max_length=100,default="")
    dcf = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    logo_url = models.CharField(max_length=100,default="")
    ipo_date = models.DateField(max_length=100, null=True)
    cik = models.CharField(max_length=100,default="")
    enterprise_value = models.DecimalField(max_digits=17, decimal_places=2, default=0)
    market_cap = models.DecimalField(max_digits=17, decimal_places=2, default=0)
    insider_ownership = models.DecimalField(max_digits=4, decimal_places=2, default=Decimal(0), validators=PERCENTAGE_VALIDATOR)
    institutional_ownership = models.DecimalField(max_digits=4, decimal_places=2, default=Decimal(0), validators=PERCENTAGE_VALIDATOR)
    is_default_image = models.BooleanField(default=False)
    is_etf = models.BooleanField(default=False)
    is_actively_traded = models.BooleanField(default=False)
    is_adr = models.BooleanField(default=False)
    is_fund = models.BooleanField(default=False)
    change_1d = models.DecimalField(max_digits=10, decimal_places=2, null=True) 
    change_5d = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    change_1m = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    change_3m = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    change_6m = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    change_ytd = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    change_1y = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    change_3y = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    change_5y = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    change_10y = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    change_max = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    datetime_added = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.ticker

class Stock_price(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    date = models.DateField()
    open = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal(0))
    high = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal(0))
    low = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal(0))
    close = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal(0))
    volume = models.IntegerField(default=0)
    adj_close = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal(0))
    datetime_added = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.company.name + ", " + str(self.date) + ", " + str(self.close)



class Company_Fundamentals(models.Model):
    id = models.CharField(max_length=10,primary_key=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    year = models.IntegerField()
    date_col = models.DateField()
    currency = models.CharField(max_length=10, default="USD")
    revenue = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    cogs = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    gross_profit = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    gross_profit_margin = models.DecimalField(max_digits=10, decimal_places=6, default=Decimal(0))
    research_and_development_exp = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    general_and_administrative_exp = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    selling_and_marketing_exp = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    selling_general_and_admin_exp = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    other_expenses = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    operating_expenses = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    cogs_and_expenses = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    interest_income = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    interest_expense = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    depreciation_and_amortization = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    ebitda = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    ebitda_margin = models.DecimalField(max_digits=10, decimal_places=6, default=Decimal(0))
    ebit = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    ebit_margin = models.DecimalField(max_digits=10, decimal_places=6, default=Decimal(0))
    total_other_income_expenses = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    income_before_tax = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    income_before_tax_margin = models.DecimalField(max_digits=10, decimal_places=6, default=Decimal(0))
    income_tax_expense = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    net_income = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    net_income_margin = models.DecimalField(max_digits=10, decimal_places=6, default=Decimal(0))
    eps = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    eps_diluted = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    weighted_average_shares = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    weighted_average_shares_diluted = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))

    cash_and_cash_equivalents = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    short_term_investments = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    cash_and_short_term_investments = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    net_receivables = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    inventory_balance_sheet = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    other_current_assets = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    total_current_assets = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    pp_and_e = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    goodwill = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    intangible_assets = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    goodwill_and_intangible_assets = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    long_term_investments = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    tax_assets = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    other_non_current_assets = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    total_non_current_assets = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    other_assets = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    total_assets = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    accounts_payable_balance_sheet = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    short_term_debt = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    tax_payable = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    deferred_revenue_current = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    other_current_liabilities = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    total_current_liabilities = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    long_term_debt = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    deferred_revenue_non_current = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    deferred_tax_liabilities_non_current = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    other_non_current_liabilities = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    total_non_current_liabilities = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    other_liabilities = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    capital_lease_obligations = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    total_liabilities = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    preferred_stock = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    common_stock = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    retained_earnings = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    accumulated_other_comprehensive_income_loss = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    other_total_stockholders_equity = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    total_stockholders_equity = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    total_liabilities_and_stockholders_equity = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    minority_interest = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    total_equity = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    total_liabilities_and_equity = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    total_investments = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    total_debt = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    net_debt = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))

    net_income_cash_flow = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    depreciation_and_amortization_cash_flow = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    deferred_income_tax = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    stock_based_compensation = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    change_in_working_capital = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    accounts_receivables_cash_flow = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    inventory_cash_flow = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    accounts_payable_cash_flow = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    other_working_capital = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    other_non_cash_items = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    net_cash_provided_by_operating_activities = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    investments_in_PP_and_E = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    aquisitions_net = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    purchase_of_investments = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    sales_maturities_of_investments = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    other_investing_activities = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    net_cash_used_for_investing_activities = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    debt_repayment = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    common_stock_issued = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    common_stock_repurchased = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    dividens_paid = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    other_financing_activities = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    net_cash_used_for_financing_activities = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    effects_of_forex_changes_on_cash = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    net_change_in_cash = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    cash_at_the_end_of_period = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    cash_at_the_beginning_of_period = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    operating_cash_flow = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    capex = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))
    free_cash_flow = models.DecimalField(max_digits=20, decimal_places=2, default=Decimal(0))

    datetime_added = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.company.name + ", " + str(self.year)



class Company_alternative_data(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    date_col = models.DateField()
    


    def __str__(self):
        return self.company.name + ", " + str(self.date_col)