# Generated by Django 4.0.5 on 2022-06-30 23:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AV_Analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_alternative_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_col', models.DateField()),
                ('investors_holding', models.IntegerField()),
                ('last_investors_holding', models.IntegerField()),
                ('investors_holding_change', models.IntegerField()),
                ('number_of_13F_shares', models.IntegerField()),
                ('last_number_of_13F_shares', models.IntegerField()),
                ('number_of_13F_shares_change', models.IntegerField()),
                ('total_invested', models.IntegerField()),
                ('last_total_invested', models.IntegerField()),
                ('total_invested_change', models.IntegerField()),
                ('ownership_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('last_ownership_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('ownership_percent_change', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('new_positions', models.IntegerField()),
                ('last_new_positions', models.IntegerField()),
                ('new_positions_change', models.IntegerField()),
                ('increased_positions', models.IntegerField()),
                ('last_increased_positions', models.IntegerField()),
                ('increased_positions_change', models.IntegerField()),
                ('closed_positions', models.IntegerField()),
                ('last_closed_positions', models.IntegerField()),
                ('closed_positions_change', models.IntegerField()),
                ('reduced_positions', models.IntegerField()),
                ('last_reduced_positions', models.IntegerField()),
                ('reduced_positions_change', models.IntegerField()),
                ('total_calls', models.IntegerField()),
                ('last_total_calls', models.IntegerField()),
                ('total_calls_change', models.IntegerField()),
                ('total_puts', models.IntegerField()),
                ('last_total_puts', models.IntegerField()),
                ('total_puts_change', models.IntegerField()),
                ('putcall_ratio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('last_putcall_ratio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('putcall_ratio_change', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AV_Analytics.company')),
            ],
        ),
    ]
