# Generated by Django 4.0.5 on 2022-07-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AV_Analytics', '0004_company_change_10y_company_change_1d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_fundamentals',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
